### ISSUE TITLE
Replaced BN with IABN during training? Page6

### ISSUE THREAD

**Issue by annny001** [TaesikGong/NOTE#3]
In the paper, " In NOTE, we replaced BN with IABN during training."  NOTE is a TTA model, so why need "training"?

**Comment by TaesikGong** [comment]
Hi,

Thank you for your interest in our paper. The “training” mentioned refers to the pre-training stage before deployment. This stage is the same as the traditional pre-training stage, except that we use IABN layers instead of BN layers.
